# Generated by Django 4.2.6 on 2023-10-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_alter_unidade_cnes'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='rt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
