# Generated by Django 5.0b1 on 2023-11-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0003_unidade_rt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='cep',
            field=models.CharField(max_length=9),
        ),
    ]
