# Generated by Django 5.0b1 on 2023-11-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_alter_log_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='dados_antes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='dados_depois',
            field=models.TextField(blank=True, null=True),
        ),
    ]
