# Generated by Django 5.0b1 on 2023-11-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_controletotal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControleTotal',
        ),
    ]
